### ISSUE TITLE
[Bug] Nested <button> in Sidebar.js

### ISSUE THREAD

**Issue by CyberCyclone** [creativetimofficial/ct-purity-ui-dashboard-pro#1]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/purity-ui-dashboard-pro/
### Operating System
NA
### Device
NA
### Browser & Version
NA
### Steps to reproduce
In the React Sidebar.js component, there is a `<AccordionButton>` with a `<Button>` nested underneath it. Since they're both based on a Button, the outputted HTML is invalid. This causes build issues when converting the React App to Next.js.
### What is expected?
`<Button>` should not be nested under `<AccordionButton>`
### What is actually happening?
-

---
### Solution
The inner `<Button>` should probably be a `<Box>`

**Comment by simmmpleweb** [comment]
Hi, @CyberCyclone ! Thanks for using our products. We changed the nested <Button> into <Text>, so now there should be no problem!
