### ISSUE TITLE
[Bug] theme fontSizes and lineHeights sttings are ignored by extendTheme function

### ISSUE THREAD

**Issue by haw0k** [creativetimofficial/ct-purity-ui-dashboard-pro#4]
### Version
2.0.2
### Reproduction link
https://demos.creative-tim.com/purity-ui-dashboard/
### Operating System
elementary OS 6.1 Jólnir
### Device
PC
### Browser & Version
Firefox 105.0.1
### Steps to reproduce
1. open src/theme.js
2. add following to the extendTheme prop object
fontSizes: { "4xl": "34px" }, lineHeights: { "4xl": "40px"},
3. add to any layout
<Heading as="h1" size="4xl" textAlign="center" color="teal.300">Page Not Found</Heading>
4. Check the actual font-size and line-height size in browser
### What is expected?
<h1 class="chakra-heading css-1q3labz">Page Not Found</h1>
with `font-size=34px` and `line-height=40px`
### What is actually happening?
<h1 class="chakra-heading css-1q3labz">Page Not Found</h1>
`font-size: 72px` and `line-height: 72px`

---

**Comment by tdumitrache** [comment]
Hi haw0k,

To override the default theme styles of Chakra UI, you have 2 options:

1. Add a fontSizes object to the globalStyles in theme to override all the fontSizes in the entire project.
![image](https://user-images.githubusercontent.com/81553507/193638235-8a744d79-a874-4254-8515-fe7bce565dfc.png)
2. Or just create another file for styling the Text Component in the project with the styles that you want.

**Comment by tdumitrache** [comment]
In this example you are changing the fontSize globally, but then you use size insead of fontSize. Try to use 'sizes: { "4xl": "36px"}' instead. Also, try to google a little bit the response on how to customize the Chakra UI Theme. You'll find the answer that satisfies your needs.
Cheers!
